# Generated by Django 2.0 on 2018-01-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Access_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(max_length=100)),
                ('get_param', models.CharField(max_length=100)),
                ('post_param', models.CharField(max_length=100)),
                ('access_time', models.DateTimeField(auto_now=True)),
                ('ip_address', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=100)),
                ('user_agent', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
