# Generated by Django 2.0 on 2018-01-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=1000)),
                ('content', models.TextField(max_length=1000)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
